# Common configuration for local as well as remote environment
common: &common
  asset_host: <%= ENV["RAILS_ASSET_HOST"] %>

# Configuration specific to local environment
local: &local
  <<: *common
  redis_url: 'redis://localhost:6379'
  perform_caching: true # switch to false caching should be disabled in development environment
  
# Configuration specific to remote environment such as test/staging/production 
remote: &remote
  <<: *common
  redis_url: <%= ENV['REDIS_URL'] %>
  dynamodb_access_key_id: <%= ENV['DYNAMODB_ACCESS_KEY_ID'] %>
  dynamodb_secret_access_key: <%= ENV['DYNAMODB_SECRET_ACCESS_KEY'] %>
  dynamodb_region: <%= ENV['DYNAMODB_REGION'] %>

# Local environment
development:
  forest_env_secret: 9c388ac5a4d6e3a5df38c1f7629d5f29d2a003f2b5871ea367de4cef501fe208
  forest_auth_secret: gGV7H4FSl79Hol18awHIQg
  <<: *local
  secret_key_base: bdfd3f9673cfd43f6f63411c6b3f3300ebee904cc8811298f3df6d37212236284568df0cf5ea4cd63f6c41c7c7c0fe51ad666696467ca1f641aa84313714ff2a

test:
  <<: *remote
  secret_key_base: a6d08ca98f7f5642873b3cce59dd55b2e877ee6d74121522095f875eca1ff0fe5d11a81d00fa2bfda2f7a64b6e56fad8a471489824eb31d91548945ce9a3c2a5

staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *remote
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *remote
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
